plugins {
    // https://fabricmc.net/develop
    id 'fabric-loom' version '1.10.1' apply false

    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.107' apply false
}

allprojects {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org'
                }
            }
            filter {
                includeGroup 'org.parchmentmc.data'
            }
        }
    }
}
